config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    $routes->setExtensions(['json', 'xml']);
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'index'],['_name'=>'isHome']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect(
        '/:category/:slug', 
        [
            'controller' => 'Pages', 
            'action' => 'display'
        ],
        [
            '_name'=>'customPages'
        ]
    )
    ->setPass(['category','slug']);
    $routes->connect('/:slug', ['controller' => 'Pages', 'action' => 'display'],['_name'=>'pages'])->setPass(['slug']);

    $routes->connect('/albums/:slug', ['controller' => 'Pages', 'action' => 'albums'],['_name'=>'album_detail'])->setPass(['slug']);
    

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    
    $routes->fallbacks(DashedRoute::class);
});
Router::prefix('webadmin', function ($routes) {
    $routes->setExtensions(['json', 'xml']);
    // All routes here will be prefixed with `/admin`
    // And have the prefix => admin route element added.
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'index']);
    $routes->connect('/logout', ['controller' => 'Pages', 'action' => 'logout']);
    $routes->connect('/edit-profile', ['controller' => 'Pages', 'action' => 'editProfile']);
    $routes->connect('/activites-log', ['controller' => 'Pages', 'action' => 'activitiesLog']);
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes. See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Table/ContentsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use App\Model\Behavior\Imagine as Imagine;
/**
 * Contents Model
 *
 * @property \App\Model\Table\ContentsCategoriesTable|\Cake\ORM\Association\BelongsTo $ContentsCategories
 * @property \App\Model\Table\LinksTable|\Cake\ORM\Association\HasMany $Links
 *
 * @method \App\Model\Entity\Content get($primaryKey, $options = [])
 * @method \App\Model\Entity\Content newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Content[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Content|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Content patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Content[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Content findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class ContentsTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('contents');
        $this->setDisplayField('title');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('ContentsCategories', [
            'foreignKey' => 'contents_category_id',
            'joinType' => 'INNER'
        ]);
        $this->hasMany('Links', [
            'foreignKey' => 'content_id'
        ]);
        $this->hasMany('RelatedContents', [
            'foreignKey' => 'created_by',
            'bindingKey' => 'created_by',
            'className' => 'Contents',
        ]);
        $this->belongsTo('CreatedUsers', [
            'foreignKey' => 'created_by',
            'className'=>'Users'
        ]);
        $this->belongsTo('ModifiedUsers', [
            'foreignKey' => 'modified_by',
            'className'=>'Users'
        ]);
        $this->addBehavior('Josegonzalez/Upload.Upload', [
            'picture' => [
                'fields' => [
                    'dir' => 'picture_dir',
                ],
                'path' => 'webroot{DS}assets{DS}content{DS}{year}{month}{DS}picture{DS}',
                'transformer' =>  function ($table, $entity, $data, $field, $settings) {
                    $imagineComponent = new Imagine;
                    $extension  = pathinfo($data['name'], PATHINFO_EXTENSION);
                    $tmp        = tempnam(sys_get_temp_dir(), 'upload') . '.' . $extension;
                    $source     = $data['tmp_name'];
                    $width      = 600;
                    $height     = 600;
                    $imagineComponent->gdImageCropAndSave($source, $tmp,['width'=>$width,'height'=>$height]);
                    
                    $tmp_2        = tempnam(sys_get_temp_dir(), 'upload') . '.' . $extension;
                    $source     = $data['tmp_name'];
                    $width      = 600;
                    $height     = 600;
                    $imagineComponent->resize($source, $tmp_2,['width'=>$width,'height'=>$height]);
                    return [
                        $data['tmp_name'] => $data['name'],
                        $tmp => 'thumbnail-' . $data['name'],
                        $tmp_2 => 'resize-' . $data['name'],
                    ];
                },
                'keepFilesOnDelete' => false
            ]
        ]);
        $this->addBehavior('AuditStash.AuditLog');
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

            $validator
            ->scalar('title')
            ->maxLength('title', 225)
            ->requirePresence('title', 'create')
            ->notEmpty('title');

        $validator
            ->scalar('contents_category_id')
            ->integer('id')
            ->requirePresence('contents_category_id', 'create')
            ->notEmpty('contents_category_id');

        $validator
            ->add('picture', 'file', [
            'rule' => ['mimeType', ['image/jpeg', 'image/png', 'image/jpg']],
            'on' => function ($context) {
                return !empty($context['data']['picture']);
            },
            'message'=>'Only JPEG,JPG and PNG allowed'])
            ->allowEmpty('picture');

        $validator
            ->scalar('body')
            ->requirePresence('body', 'create')
            ->allowEmpty('body');

        $validator
            ->integer('sort')
            ->requirePresence('sort', 'create')
            ->allowEmpty('sort');
        
            return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['contents_category_id'], 'ContentsCategories'));

        return $rules;
    }
}

src/Controller/Webadmin/ApisController.php
<?php
namespace App\Controller\Webadmin;

use App\Controller\AppController;
use Cake\Routing\Router;

class ApisController extends AppController
{
    public function initialize()
    {
        parent::initialize();
        $this->loadComponent('RequestHandler');
        if(php_sapi_name() !== 'cli'){
            $this->Auth->allow([
              'getLinkBySiteMap', 'getDoctors', 'getPolyclinics'
            ]);
        }
    }

    public function getLinkBySiteMap($id)
    {
        $this->loadModel('Links');
        $parents = $this->Links->find('treeList',[
            'conditions' => [
                'links_map_id' => $id
            ]
        ]);
        $this->set('parents',$parents);
        $this->set('_serialize','parents');
    }

    public function getDoctors($id)
    {
        $this->loadModel('Doctors');
        if($this->request->is('ajax')){
            $search = "";
            if($this->request->query('search')){
                $search = $this->request->query('search');
            }
            $data = $this->Doctors->find('all',[
                'conditions' => [
                    'id'=> $id
                ],
                'order' => [
                    'name' => 'ASC'
                ]
            ]);
            $results = [];
            $a =0;
            foreach($data as $key => $val){
                $results[$a]['id'] = $val->id;
                $results[$a]['text'] = $val->name;
                $a++;
            }
            $this->set(compact('results'));
            $this->set('_serialize',['results']);
        }
    }
    public function getPolyclinics($id)
    {
        $this->loadModel('Polyclinics');
        if($this->request->is('ajax')){
            $search = "";
            if($this->request->query('search')){
                $search = $this->request->query('search');
            }
            $data = $this->Polyclinics->find('all',[
                'conditions' => [
                    'id'=> $id
                ],
                'order' => [
                    'polyclinic' => 'ASC'
                ]
            ]);
            $results = [];
            $a =0;
            foreach($data as $key => $val){
                $results[$a]['id'] = $val->id;
                $results[$a]['text'] = $val->name;
                $a++;
            }
            $this->set(compact('results'));
            $this->set('_serialize',['results']);
        }
    }
}

src/Controller/Webadmin/AppSettingsController.php
<?php
namespace App\Controller\Webadmin;

use App\Controller\AppController;
use Cake\Routing\Router;

/**
 * AppSettings Controller
 *
 * @property \App\Model\Table\AppSettingsTable $AppSettings
 *
 * @method \App\Model\Entity\AppSetting[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class AppSettingsController extends AppController
{

    public function initialize()
    {
        parent::initialize();
        $this->loadComponent('Imagine');
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $appSettings = $this->AppSettings->find('all',[
            'conditions' => [
                'status' => 0
            ]
        ]);
        $settings = [];
        foreach($appSettings as $key => $r){
            $settings += [str_replace(".","_",$r->keyField) => $r];
        }

        $appSettings = $settings;
        $dataSave = $this->AppSettings->newEntity();
        if ($this->request->is(['patch', 'post', 'put'])) {
            $data = $this->request->data;
            $dataSave = $this->AppSettings->patchEntity($dataSave,$data);
            if(empty($dataSave->errors())){
                foreach($data as $w => $d){
                    $id = $appSettings[$w]['id'];
                    $dataOriginal = $this->AppSettings->get($id);
                    $valueSave = "";
                    if($w == 'App_Logo'){
                        $source = $d['tmp_name'];
                        if(!empty($source)){
                            $uploadFolder = WWW_ROOT.'assets'.DS.'webadmin'.DS.'img'.DS.'logo';
                            $saveDir = '/webroot/assets/webadmin/img/logo';
                            $extension  = pathinfo($d['name'], PATHINFO_EXTENSION);
                            $tmp        = $uploadFolder.'.'. $extension;
                            $saveDir    = $saveDir.'.'.$extension;
                            $width  = $data['App_Logo_Width'];
                            $height = $data['App_Logo_Height'];
                            $this->Imagine->gdImageCropAndSave($source, $tmp,['width'=>$width,'height'=>$height]);
                            $valueSave = $saveDir;
                        }
                    }elseif($w == 'App_Logo_Login'){
                        $source = $d['tmp_name'];
                        if(!empty($source)){
                            $uploadFolder = WWW_ROOT.'assets'.DS.'webadmin'.DS.'img'.DS.'logo_login';
                            $saveDir = '/webroot/assets/webadmin/img/logo_login';
                            $extension  = pathinfo($d['name'], PATHINFO_EXTENSION);
                            $tmp        = $uploadFolder.'.'. $extension;
                            $saveDir    = $saveDir.'.'.$extension;
                            $width  = $data['App_Logo_Login_Width'];
                            $height = $data['App_Logo_Login_Height'];
                            $this->Imagine->gdImageCropAndSave($source, $tmp,['width'=>$width,'height'=>$height]);
                            $valueSave = $saveDir;
                        }
                    }elseif($w == 'App_Login_Cover'){
                        $source = $d['tmp_name'];
                        if(!empty($source)){
                            $uploadFolder = WWW_ROOT.'assets'.DS.'webadmin'.DS.'img'.DS.'cover_login';
                            $saveDir = '/webroot/assets/webadmin/img/cover_login';
                            $extension  = pathinfo($d['name'], PATHINFO_EXTENSION);
                            $tmp        = $uploadFolder.'.'. $extension;
                            $saveDir    = $saveDir.'.'.$extension;
                            $width  = 1920;
                            $height = 1080;
                            $this->Imagine->gdImageCropAndSave($source, $tmp,['width'=>$width,'height'=>$height]);
                            $valueSave = $saveDir;
                        }
                    }elseif($w == 'App_Favico'){
                        $source = $d['tmp_name'];
                        if(!empty($source)){
                            $uploadFolder = WWW_ROOT.'assets'.DS.'webadmin'.DS.'img'.DS.'favico';
                            $saveDir = '/webroot/assets/webadmin/img/favico';
                            $extension  = pathinfo($d['name'], PATHINFO_EXTENSION);
                            $tmp        = $uploadFolder.'.'. $extension;
                            $saveDir    = $saveDir.'.'.$extension;
                            $width  = 30;
                            $height = 30;
                            $this->Imagine->gdImageCropAndSave($source, $tmp,['width'=>$width,'height'=>$height]);
                            $valueSave = $saveDir;
                        }
                    }else{
                        $valueSave = $d;
                    }
                    if(!empty($valueSave)){
                        $dataUpdate['id'] = $id;
                        $dataUpdate['valueField'] = $valueSave;
                        $this->AppSettings->save($this->AppSettings->patchEntity($dataOriginal,$dataUpdate,['validate'=>false]));
                    }
                }

                $this->Flash->success(__('The app setting has been saved. Please, try again.'));
                $this->Redis->destroyCacheAppSettings();
                $this->Redis->createCacheAppSettings();
                return $this->redirect(['action'=>'index']);
            }else{
                $this->Flash->error(__('The app setting could not be saved. Please, try again.'));
            }
            
        }
        $titleModule = "App Settings";
        $titlesubModule = "Edit ".$titleModule;
        $breadCrumbs = [
            Router::url(['action' => 'index']) => "Edit ".$titleModule,
        ];
        $this->set(compact('titleModule','breadCrumbs','titlesubModule','appSettings','dataSave'));
    }

}

src/Template/Webadmin/Contents/index.ctp
<?php
    $rightButton = '<a href="'.$this->Url->build(['action'=>'add']).'" class="btn btn-primary m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
                        <span>
                            <i class="la la-plus"></i>
                            <span>
                                Create
                            </span>
                        </span>
                    </a>';
?>
<?=$this->element('widget/index',['rightButton' => $rightButton]);?>
<?php
    $deleteUrl    = $this->Url->build(['action'=>'delete'])."/";
    if($this->Acl->check(['action'=>'delete']) == false){
        $deleteUrl = "";
    }
    $editUrl      = $this->Url->build(['action'=>'edit'])."/";
    if($this->Acl->check(['action'=>'edit']) == false){
        $editUrl = "";
    }
    $viewUrl      = $this->Url->build(['action'=>'view'])."/";
    if($this->Acl->check(['action'=>'view']) == false){
        $viewUrl = "";
    }
?>
<?=$this->Html->scriptBlock('
jQuery(document).ready(function() {
    var deleteUrl = "'.$deleteUrl.'";
    var editUrl = "'.$editUrl.'";
    var viewUrl = "'.$viewUrl.'";
    var columnData = [{
        field: "Contents.id",
        title: "ID",
        sortable: false,
        width: 40,
        selector: false,
        textAlign: "center",
        template: function(t) {
            return t.id
        }
    },  {
        field: "ContentsCategories.title",
        title: "Category",
        sort : \'asc\',
        template: function(t) {
            return t.contents_category.title
        }
    },  {
        field: "Contents.title",
        title: "Title",
        sort : \'asc\',
        template: function(t) {
            return t.title
        }
    },  {
        field: "Contents.created",
        title: "Created",
        sort : \'asc\',
        template: function(t) {
            return Utils.dateIndonesia(t.created,true,true)
        }
    },  {
        field: "Contents.modified",
        title: "Modified",
        sort : \'asc\',
        template: function(t) {
            return Utils.dateIndonesia(t.modified,true,true)
        }
    },
    {
        field: "actions",
        width: 100,
        title: "Actions",
        sortable: false,
        overflow: "visible",
        template: function(t) {
            var btn =  \'<div class="dropdown"><a href="#" class="btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" data-toggle="dropdown"><i class="la la-ellipsis-h"></i></a>  <div class="dropdown-menu dropdown-menu-right">\'
            var btnList = \'\';
            if(viewUrl != ""){
                btnList += \'<a class="dropdown-item" href="\'+viewUrl+t.id+\'"><i class="flaticon-search-1"></i> View</a>\';
            }
            if(deleteUrl != ""){
                btnList += \'<a class="btn-delete-on-table dropdown-item" href="\'+deleteUrl+t.id+\'"><i class="flaticon-cancel"></i> Delete</a>\';
            }
            if(editUrl != ""){
                btnList += \'<a class="dropdown-item" href="\'+editUrl+t.id+\'"><i class="flaticon-edit"></i> Edit</a>\';
            }
            
            if(btnList == ""){
                btn = "";
            }else{
                btn += btnList;
                btn += \'</div></div>\';
            }
            return btn;
        }
    }];
    DatatableRemoteAjax.init("",columnData)
});',['block'=>'script']);

src/Template/Webadmin/Contents/view.ctp
<div class="m-portlet m-portlet--tab">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                    <?=$titlesubModule;?>
                </h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                </li>
            </ul>
        </div>
    </div>
    <div class="m-portlet__body">
        <!--begin: Datatable -->
        <table class="table">
        <tr>
            <th scope="row" width="20%"><?= __('Title') ?></th>
            <td><?= h($content->title) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Content Category') ?></th>
            <td><?= h($content->contents_category->title) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Thumbnail') ?></th>
            <td><img src="<?= $this->Utilities->generateUrlImage($content->picture_dir,"thumbnail-".$content->picture) ?>" width="150px" style="max-width:100%" ></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Cover') ?></th>
            <td><img src="<?= $this->Utilities->generateUrlImage($content->cover_dir,"thumbnail-".$content->cover) ?>" width="750px" style="max-width:100%" ></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Meta Description') ?></th>
            <td><?= $content->meta_description?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Meta Keyword') ?></th>
            <td><?= $content->meta_keyword?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Body') ?></th>
            <td><?= $content->body?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Id') ?></th>
            <td><?= $this->Number->format($content->id) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Created') ?></th>
            <td><?= h($content->created) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Modified') ?></th>
            <td><?= h($content->modified) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Status') ?></th>
            <td><?= $this->Utilities->statusLabel($content->status)?></td>
        </tr>
        </table>
        <!--end: Datatable -->
    </div>
</div>